Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -56,23 +56,23 @@ jobs:
       - name: Ping the target machine
         run: |
           ping -n 4 192.168.0.186
-      - name: Test WinRM port 5985 (HTTP) connection
-        run: |
-          $server = '192.168.0.186'
-          $username = 'Administrator'
-          $password = 'Trinh2002'
+      # - name: Test WinRM port 5985 (HTTP) connection
+      #   run: |
+      #     $server = '192.168.0.186'
+      #     $username = 'Administrator'
+      #     $password = 'Trinh2002'
 
-          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
-          $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)
+      #     $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
+      #     $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)
 
-          try {
-            $session = New-PSSession -ComputerName $server -Credential $credential -ErrorAction Stop
-            Write-Host "Successfully connected to $server via WinRM"
-            Remove-PSSession $session
-          } catch {
-            Write-Error "Failed to connect to $server via WinRM"
-            exit 1
-          }
+      #     try {
+      #       $session = New-PSSession -ComputerName $server -Credential $credential -ErrorAction Stop
+      #       Write-Host "Successfully connected to $server via WinRM"
+      #       Remove-PSSession $session
+      #     } catch {
+      #       Write-Error "Failed to connect to $server via WinRM"
+      #       exit 1
+      #     }
 
       - name: Download published application
         uses: actions/download-artifact@v4
